Setup debug session

diff --git a/.github/workflows/tests-integration-reusable.yml b/.github/workflows/tests-integration-reusable.yml
--- a/.github/workflows/tests-integration-reusable.yml
+++ b/.github/workflows/tests-integration-reusable.yml
@@ -91,24 +91,26 @@ jobs:
         shepherd login service-account ${account_token}
         pool_name="tas-2_11"
         lease_id=$(shepherd create lease --duration 8h --pool ${pool_name} --pool-namespace official --namespace tas-devex --json | jq -r .id) 
-        # lease_id="32ce319e-c5e6-41f5-bde3-19b1bbeb32d9"
-        # shepherd get lease ${lease_id} --namespace gururajsh --json | jq .output > metadata.json
+        lease_id="32ce319e-c5e6-41f5-bde3-19b1bbeb32d9"
+        shepherd get lease ${lease_id} --namespace gururajsh --json | jq .output > metadata.json
 
         # Give somtime for the lease to complete. Shepherd may take upto an 3 hours to create an env
         # if the pool is empty.
-        count=0
-        while [ $count -lt 360 ] ; do
-          sleep 30
-          status=$(shepherd get lease ${lease_id} --namespace tas-devex --json | jq -r .status)
-          if [ $status == "LEASED" ] ; then
-            shepherd get lease ${lease_id} --namespace tas-devex --json | jq .output > metadata.json
-            break
-          elif [ $status == "FAILED" -o $status == "EXPIRED" ] ; then
-            echo "There was an error obtaining the lease. Lease status is ${status}."
-            exit 1
-          fi
-          count=$(($count+1))
-        done
+        # count=0
+        # while [ $count -lt 360 ] ; do
+        #   sleep 30
+        #   status=$(shepherd get lease ${lease_id} --namespace tas-devex --json | jq -r .status)
+        #   if [ $status == "LEASED" ] ; then
+        #     shepherd get lease ${lease_id} --namespace tas-devex --json | jq .output > metadata.json
+        #     break
+        #   elif [ $status == "FAILED" -o $status == "EXPIRED" ] ; then
+        #     echo "There was an error obtaining the lease. Lease status is ${status}."
+        #     exit 1
+        #   else
+        #     echo "Waiting for environment to be ready. Lease status is ${status}."
+        #   fi
+        #   count=$(($count+1))
+        # done
 
         env_name=$(jq -r .name metadata.json)
         cat metadata.json | jq -r '.name'
@@ -238,6 +240,10 @@ jobs:
                           use-latest-ruby-buildpack.yml"
         ./cf-deployment-concourse-tasks/bosh-deploy/task
 
+    - name: Setup tmate session
+      if: always()
+      uses: mxschmitt/action-tmate@v3
+
     - name: Set Up Go
       uses: actions/setup-go@v5
       with:
@@ -272,10 +278,6 @@ jobs:
         cf auth
 
         make integration-tests-full-ci
-
-    # - name: Setup tmate session
-    #   if: always()
-    #   uses: mxschmitt/action-tmate@v3
 
     - name: Run Integration Tests with client credentials
       if: ${{ inputs.run-with-client-creds }}
